#!/usr/bin/env python3
"""
Test script to verify vLLM returns prompt_ids with role headers included.

This tests the hypothesis that we can use vLLM's token_ids directly
without re-applying chat_template.
"""

import asyncio
import sys

from transformers import AutoTokenizer

# Add forge to path
sys.path.insert(0, "/home/felipemello/forge")

from forge.actors.generator import Generator
from vllm.engine.arg_utils import EngineArgs
from vllm.sampling_params import SamplingParams


def print_section(title):
    print("\n" + "=" * 5)
    print(title)
    print("=" * 5)


async def main():
    # Load tokenizer (same as blackjack)
    model_path = "Qwen/Qwen3-1.7B"
    tokenizer = AutoTokenizer.from_pretrained(
        model_path,
        local_files_only=True,  # Use cached files only
    )

    # CRITICAL: Enable thinking to prevent auto-wrapping
    tokenizer.enable_thinking = True

    print_section("TOKENIZER INFO")
    print(f"Model: {model_path}")
    print(f"EOS token: {tokenizer.eos_token} (id={tokenizer.eos_token_id})")
    print(f"PAD token: {tokenizer.pad_token} (id={tokenizer.pad_token_id})")
    print(f"Enable thinking: {tokenizer.enable_thinking}")

    # Setup generator
    print_section("SETTING UP GENERATOR")
    engine_args = EngineArgs(
        model=model_path,
        tensor_parallel_size=1,
        max_model_len=2048,
        enable_prefix_caching=True,
    )

    sampling_params = SamplingParams(
        temperature=0.7,
        top_p=0.9,
        max_tokens=100,
        logprobs=1,  # Request logprobs
    )

    generator = await Generator.options(
        procs=1,
        num_replicas=1,
        with_gpus=True,
    ).as_service(
        engine_args=engine_args,
        sampling_params=sampling_params,
    )

    print("✅ Generator ready")

    # Build conversation manually
    print_section("TEST 1: SIMPLE CONVERSATION")
    messages = [
        {
            "role": "system",
            "content": "You are an expert BlackJack player. Output only 'HIT' or 'STAND'.",
        },
        {"role": "user", "content": "Hand: 15, Dealer: 10"},
    ]

    # Apply chat template to get prompt text
    prompt_text = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=False,
        enable_thinking=True,  # Prevent auto-wrapper
    )

    print("\n[Prompt Text]")
    print(repr(prompt_text))

    # Tokenize locally to see what we expect
    local_tokens = tokenizer.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        enable_thinking=True,  # Prevent auto-wrapper
    )

    print(f"\n[Local Tokenization]")
    print(f"Total tokens: {len(local_tokens)}")
    print(f"First 20 tokens: {local_tokens[:20]}")

    # Generate with vLLM
    print("\n[Calling vLLM...]")

    completions = await generator.generate.route(
        prompt_text,  # Pass prompt directly, not as list
        sampling_params=sampling_params,
    )
    print(f"Type of completions: {type(completions)}")
    print(f"Length: {len(completions)}")
    completion = completions[0]  # First completion

    print_section("VLLM RESPONSE")
    print(f"\n[Response Text]")
    print(repr(completion.text))
    print(f"\n[Stop Reason]")
    print(completion.stop_reason)

    # Inspect prompt_ids
    print_section("PROMPT_IDS (from vLLM)")
    prompt_ids = completion.prompt_ids.tolist()
    print(f"Length: {len(prompt_ids)}")
    print(f"First 20 tokens: {prompt_ids[:20]}")
    print(f"Last 10 tokens: {prompt_ids[-10:]}")

    # Compare with local tokenization
    print("\n[Comparison with Local Tokenization]")
    if prompt_ids == local_tokens:
        print("✅ PERFECT MATCH! prompt_ids == local_tokens")
    else:
        print(f"❌ MISMATCH!")
        print(f"  vLLM length: {len(prompt_ids)}")
        print(f"  Local length: {len(local_tokens)}")
        if len(prompt_ids) == len(local_tokens):
            # Find first difference
            for i, (a, b) in enumerate(zip(prompt_ids, local_tokens)):
                if a != b:
                    print(f"  First diff at position {i}: vLLM={a}, local={b}")
                    break

    # Decode prompt_ids to verify it includes role headers
    print("\n[Decoded prompt_ids]")
    decoded_prompt = tokenizer.decode(prompt_ids)
    print(repr(decoded_prompt))

    # Inspect token_ids (generated content)
    print_section("TOKEN_IDS (generated by vLLM)")
    token_ids = completion.token_ids.tolist()
    print(f"Length: {len(token_ids)}")
    print(f"Tokens: {token_ids[:50] if len(token_ids) > 50 else token_ids}")

    # Decode token_ids
    print("\n[Decoded token_ids (raw generation)]")
    decoded_generation = tokenizer.decode(token_ids)
    print(repr(decoded_generation))

    # Check if last token is EOS
    print("\n[Truncation Check]")
    if len(token_ids) > 0:
        last_token = token_ids[-1]
        is_eos = last_token == tokenizer.eos_token_id
        print(f"Last token: {last_token}")
        print(f"EOS token: {tokenizer.eos_token_id}")
        print(f"Is EOS: {is_eos}")
        if not is_eos:
            print("⚠️  Generation was TRUNCATED (no EOS)")
        else:
            print("✅ Generation completed normally (has EOS)")

    # Now test: Can we extract role headers?
    print_section("EXTRACTING ROLE HEADERS")

    # Method 1: Use a dummy conversation to get header/footer
    print("\n[Method: Dummy Conversation with enable_thinking=True]")
    dummy_messages = [
        {"role": "system", "content": ""},
        {"role": "user", "content": ""},
        {"role": "assistant", "content": "X"},  # Plain content, no think tags
    ]

    base_tokens = tokenizer.apply_chat_template(
        dummy_messages[:2],
        add_generation_prompt=True,
        tokenize=True,
        enable_thinking=True,  # Prevent auto-wrapper
    )
    print(
        f"Base (sys+user+gen_prompt) decoded:\n{repr(tokenizer.decode(base_tokens))}\n"
    )

    full_tokens = tokenizer.apply_chat_template(
        dummy_messages,
        add_generation_prompt=False,
        tokenize=True,
        enable_thinking=True,  # Prevent auto-wrapper
    )
    print(
        f"Full (sys+user+assistant) decoded:\n{repr(tokenizer.decode(full_tokens))}\n"
    )

    # Extract assistant portion
    assistant_full = full_tokens[len(base_tokens) :]
    print(f"Assistant full decoded:\n{repr(tokenizer.decode(assistant_full))}\n")
    print(f"Assistant full tokens: {assistant_full}")

    # Find where "X" is
    content_tokens = tokenizer.encode("X", add_special_tokens=False)
    print(f"\nContent tokens (just 'X'): {content_tokens}")

    # Find content position
    found = False
    for i in range(len(assistant_full) - len(content_tokens) + 1):
        if assistant_full[i : i + len(content_tokens)] == content_tokens:
            role_header = assistant_full[:i]
            role_footer = assistant_full[i + len(content_tokens) :]
            print(f"\n✅ Found content at position {i}")
            print(f"\nRole header ({len(role_header)} tokens):")
            print(f"  Tokens: {role_header}")
            print(f"  Decoded: {repr(tokenizer.decode(role_header))}")
            print(f"\nRole footer ({len(role_footer)} tokens):")
            print(f"  Tokens: {role_footer}")
            print(f"  Decoded: {repr(tokenizer.decode(role_footer))}")
            found = True
            break

    if not found:
        print("❌ Could not find content in assistant tokens")
        print(f"Searching for: {content_tokens}")
        print(f"In: {assistant_full}")

    # Test: Combine header + vLLM tokens + footer
    if found:
        print_section("TESTING: header + vLLM tokens + footer")
        combined = role_header + token_ids + role_footer
        print(f"\nCombined length: {len(combined)}")
        print(f"Combined tokens (first 30): {combined[:30]}")

        # Decode combined
        decoded_combined = tokenizer.decode(combined)
        print(f"\n[Decoded Combined]")
        print(repr(decoded_combined))

        # Now add to full conversation
        print_section("FULL CONVERSATION RECONSTRUCTION")
        full_conversation = prompt_ids + combined
        print(f"Full length: {len(full_conversation)}")

        decoded_full = tokenizer.decode(full_conversation)
        print(f"\n[Decoded Full Conversation]")
        print(decoded_full)

        # Verify against expected format
        messages_with_response = messages + [
            {"role": "assistant", "content": completion.text}
        ]
        expected_tokens = tokenizer.apply_chat_template(
            messages_with_response,
            add_generation_prompt=False,
            tokenize=True,
            enable_thinking=True,  # Prevent auto-wrapper
        )

        print(f"\n[Verification]")
        print(f"Reconstructed length: {len(full_conversation)}")
        print(f"Expected length: {len(expected_tokens)}")

        if full_conversation == expected_tokens:
            print("✅✅✅ PERFECT MATCH! We can use vLLM tokens directly!")
        else:
            print("❌ Mismatch - need to investigate")
            # Find first difference
            min_len = min(len(full_conversation), len(expected_tokens))
            for i in range(min_len):
                if full_conversation[i] != expected_tokens[i]:
                    print(f"  First diff at position {i}:")
                    print(f"    Reconstructed: {full_conversation[max(0,i-5):i+10]}")
                    print(f"    Expected: {expected_tokens[max(0,i-5):i+10]}")
                    break
            if len(full_conversation) != len(expected_tokens):
                print(
                    f"  Length mismatch by {abs(len(full_conversation) - len(expected_tokens))} tokens"
                )

    # Cleanup
    print_section("CLEANUP")
    await generator.shutdown()
    print("✅ Done")


if __name__ == "__main__":
    asyncio.run(main())
