# On-Policy Distillation: Qwen 0.6B (student) learning from Qwen 8B (teacher)
# >>> python -m apps.on-policy-distillation.main --config apps/on-policy-distillation/qwen_0_6b_to_8b.yaml

# Global configuration
train_batch_size: 4  # Number of trajectories per training step
max_req_tokens: 512
max_res_tokens: 65536
student_model: "Qwen/Qwen3-1.7B"
teacher_model: "Qwen/Qwen3-8B"

# Dataset configuration
dataset:
  path: "open-thoughts/OpenThoughts3-1.2M"
  split: "train"
  domain: "math"

# Student Generator configuration (inference model)
student_generator:
  engine_args:
    model: ${student_model}
    tensor_parallel_size: 1
    pipeline_parallel_size: 1
    enforce_eager: false
  sampling_params:
    n: 2  # Single response per prompt
    max_tokens: ${max_res_tokens}
    temperature: 1.0
    top_p: 0.95

# Student Trainer configuration
trainer:
  model:
    name: qwen3
    flavor: 1.7B
    hf_assets_path: hf://${student_model}
  optimizer:
    name: AdamW
    lr: 5e-5  # Higher LR for distillation
    eps: 1e-8
  lr_scheduler:
    warmup_steps: 10
  training:
    local_batch_size: ${train_batch_size}  # Per-device batch size
    seq_len: 66048
    max_norm: 1.0
    steps: 10000
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 2
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
    disable_loss_parallel: true
  checkpoint:
    enable: true
    # folder: ./checkpoint_student
    initial_load_path: hf://${student_model}
    initial_load_in_hf: true
    last_save_in_hf: true
    interval: 500
    async_mode: "disabled"
  activation_checkpoint:
    mode: selective
    selective_ac_option: op

# Teacher model configuration
teacher:
  model:
    name: qwen3
    flavor: 8B
    hf_assets_path: hf://${teacher_model}
  training:
    seq_len: ${trainer.training.seq_len}
    dtype: bfloat16
    gc_freq: 1
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: 2
    tensor_parallel_degree: 1  # Use 2 GPUs for teacher
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
  checkpoint:
    enable: true
    initial_load_path: hf://${teacher_model}
    initial_load_in_hf: true

# Resource allocations (3 GPUs total)
services:
  student_generator:
    procs: 1  # Student inference: 1 GPU
    num_replicas: 1
    mesh_name: student_generator
    with_gpus: true
  teacher:
    procs: 2 # Teacher: 2 GPUs with TP
    num_replicas: 1
    mesh_name: teacher
    with_gpus: true
  trainer:
    procs: 2  # Student training: shares GPU with student_generator
    num_replicas: 1
    mesh_name: trainer
    with_gpus: true
