# GRPO Training Configuration

# Global configuration
group_size: 2
batch_size: 8
max_req_tokens: 512
max_res_tokens: 512
model: "Qwen/Qwen3-8B"

# Dataset configuration
dataset:
  path: "openai/gsm8k"
  revision: "main"
  data_split: "train"
  streaming: true
  model: ${model}
# Policy configuration
policy:
  engine_config:
    model: ${model}
    tensor_parallel_size: 4
    pipeline_parallel_size: 1
    enforce_eager: false
  sampling_config:
    n: ${group_size}
    max_tokens: ${max_res_tokens}
    temperature: 1.0
    top_p: 1.0

# Trainer configuration
trainer:
  model:
    name: qwen3
    flavor: 8B
    hf_assets_path: hf://${model}
  optimizer:
    name: AdamW
    lr: 1e-5
    eps: 1e-8
  lr_scheduler:
    warmup_steps: 1
  training:
    local_batch_size: ${batch_size}
    seq_len: 2048
    max_norm: 1.0
    steps: 5
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    data_parallel_shard_degree: -1
    tensor_parallel_degree: 1
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
    disable_loss_parallel: true
  checkpoint:
    enable: true
    initial_load_path: hf://${model}
    initial_load_in_hf: true
    last_save_in_hf: true
    interval: 500
    async_mode: "disabled"
  activation_checkpoint:
    mode: selective
    selective_ac_option: op


# Replay buffer configuration
replay_buffer:
  # batch_size: ${batch_size}
  batch_size: 1
  max_policy_age: 1 # Async by 1
  # dp_size: ${trainer.parallelism.data_parallel_replicate_degree}
  dp_size: 8

# Reference model configuration
ref_model:
  model:
    name: qwen3
    flavor: 8B
    hf_assets_path: hf://${model}
  compile:
    enable: false
  parallelism:
    data_parallel_replicate_degree: 1
    tensor_parallel_degree: 8
    pipeline_parallel_degree: 1
    context_parallel_degree: 1
    expert_parallel_degree: 1
    disable_loss_parallel: false
  checkpoint:
    initial_load_path: hf://${model}
    initial_load_in_hf: true


services:
  dataset:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
  policy:
    procs_per_replica: ${policy.engine_config.tensor_parallel_size}
    num_replicas: 1
    hosts_per_replica: 1
    with_gpus: true
  trainer:
    procs_per_replica: 8
    num_replicas: 1
    hosts_per_replica: 1
    with_gpus: true
  replay_buffer:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
  ref_model:
    hosts_per_replica: 1
    procs_per_replica: 8
    num_replicas: 1
    with_gpus: true
  compute_advantages:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false
  reward_actor:
    procs_per_replica: 1
    num_replicas: 1
    with_gpus: false