name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

jobs:
  test-cpu:
    name: Test CPU
    uses: ./.github/workflows/tests-cpu.yaml
    with:
      artifact-name: forge-cpu-${{ github.sha }}

  status-check:
    name: Status Check
    runs-on: ubuntu-latest
    needs: [test-cpu]
    if: always()
    steps:
      - name: Check all jobs status
        run: |
          if [[ "${{ needs.test-cpu.result }}" != "success" ]]; then
            echo "One or more jobs failed"
            exit 1
          else
            echo "All jobs passed"
          fi
