name: Unit Test

on:
  pull_request:


jobs:
  unit_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Setup conda env
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          miniconda-version: "latest"
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      # TODO: these are just debug changes
      - name: print some stuff
        run: |
          echo "Conda prefix: ${CONDA_PREFIX}"
          echo "Conda: $CONDA"
          echo "Current path: ${{ env.PATH }}""
          conda env list
          echo "before export"
          echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
          echo "LD_PRELOAD: ${LD_PRELOAD}"
          ls -ahl ${CONDA_PREFIX}
          ls -ahl ${CONDA_PREFIX}/lib
          export LD_PRELOAD=${CONDA_PREFIX}/lib/libpython3.10.so.1.0:${LD_PRELOAD}
          export LD_LIBRARY_PATH=${CONDA_PREFIX}/lib/libpython3.10.so.1.0:${LD_LIBRARY_PATH}
          echo "after export"
          echo "LD_LIBRARY_PATH: ${LD_LIBRARY_PATH}"
          echo "LD_PRELOAD: ${LD_PRELOAD}"
